<?php
header('Content-Type: application/json');

// Arrays of words
$ideasAdj = ["cool", "funny", "interesting", "weird", "strange", "crazy", "awesome", "amazing", "boring", "dull", "exciting", "fascinating", "unusual", "odd", "peculiar", "unique", "extraordinary", "fantastic", "incredible", "marvelous", "outstanding", "remarkable", "spectacular", "stunning", "wonderful", "beautiful", "gorgeous", "handsome", "pretty", "ugly", "hideous", "homely", "plain", "attractive", "charming", "cute", "delightful", "pleasant", "pleasing", "satisfying", "unattractive", "disgusting", "gross", "revolting", "repulsive", "sickening", "vile", "abhorrent", "appalling", "dreadful", "frightful", "ghastly", "gruesome", "horrible", "horrific", "terrible", "awful", "bad", "poor", "sad", "tragic", "unfortunate", "wretched", "cheerful", "happy", "joyful", "merry", "mirthful", "jolly", "jovial", "jocund", "gleeful", "carefree", "delighted", "ecstatic", "elated", "enraptured", "euphoric", "exultant", "radiant", "sunny", "blithe", "buoyant", "lighthearted", "optimistic", "playful", "sanguine", "upbeat", "depressed", "despondent", "disconsolate", "dismal", "downcast", "downhearted", "forlorn", "gloomy", "glum", "melancholy", "mournful", "sad", "sorrowful", "unhappy", "wretched", "angry", "annoyed", "cross", "displeased", "furious", "incensed", "indignant", "irritated", "offended", "resentful", "enraged", "exasperated", "infuriated", "livid", "mad"];
$ideasNoun = ["dog", "cat", "bird", "fish", "hamster", "rabbit", "turtle", "snake", "lizard", "frog", "toad", "salamander", "newt", "iguana", "chameleon", "gecko", "crocodile", "alligator", "dinosaur", "mammal", "reptile", "amphibian", "fish", "bird", "insect", "arachnid", "crustacean", "mollusk", "worm", "snail", "slug", "jellyfish", "starfish", "sea urchin", "coral", "anemone", "sponge", "plankton", "algae", "fungus", "mushroom", "moss", "fern", "flower", "tree", "shrub", "grass", "weed", "vine", "bush", "cactus", "succulent", "herb", "spice", "fruit", "vegetable", "nut", "seed", "grain", "legume", "berry", "melon", "citrus", "apple", "pear", "peach", "plum", "cherry", "apricot", "nectarine", "grape", "raisin", "date", "fig", "olive", "coconut", "banana", "pineapple", "mango", "papaya", "kiwi", "strawberry", "blueberry", "raspberry", "blackberry", "cranberry", "gooseberry", "currant", "elderberry", "boysenberry", "loganberry", "mulberry", "watermelon", "cantaloupe", "honeydew", "squash", "pumpkin", "zucchini", "cucumber", "tomato", "potato", "carrot", "onion", "garlic", "ginger", "radish", "turnip", "beet", "rutabaga", "parsnip", "celery", "lettuce", "spinach", "kale", "chard", "collard", "mustard", "cabbage", "broccoli", "cauliflower", "brussels sprout", "kohlrabi", "asparagus", "artichoke"];
$ideasVerb = ["run", "jump", "hop", "skip", "walk", "crawl", "swim", "fly", "soar", "glide", "float", "drift", "sail", "row", "paddle", "pedal", "drive", "ride", "skate", "ski", "snowboard", "surf", "climb", "hike", "camp", "fish", "hunt", "shoot", "trap", "gather", "forage", "harvest", "plant", "grow", "cultivate", "tend", "prune", "trim", "mow", "rake", "shovel", "dig", "till", "plow", "sow", "reap", "thresh", "winnow", "mill", "bake", "cook", "fry", "boil", "grill", "roast", "toast", "steam", "poach", "stew", "braise", "saute", "simmer", "broil", "bake", "barbecue", "smoke", "cure", "pickle", "preserve", "can", "freeze", "dry", "dehydrate", "ferment", "brew", "distill", "mash", "muddle", "stir", "shake", "strain", "pour", "drink", "sip", "guzzle", "swallow", "chew", "bite", "nibble", "taste", "savor", "lick", "suck", "kiss", "hug", "cuddle", "snuggle", "caress", "stroke", "pet", "scratch", "rub", "massage", "knead", "squeeze", "pinch", "poke", "prod", "punch", "kick", "slap", "hit", "smack", "spank", "whip", "beat", "thrash", "whack", "pound", "pummel", "pelt", "wallop", "clobber", "batter", "assault", "attack", "ambush", "mug", "rob", "steal", "snatch", "grab", "take", "lift", "carry", "haul", "drag", "pull", "push", "shove"];

// Function to generate an idea
function generateIdea($adjectives, $verbs, $nouns) {
	$adj = $adjectives[array_rand($adjectives)];
	$verb = $verbs[array_rand($verbs)];
	$noun = $nouns[array_rand($nouns)];
	
	return "The $adj $noun $verb.";
}

// Generate and return an idea
$idea = generateIdea($ideasAdj, $ideasVerb, $ideasNoun);
echo json_encode(['idea' => $idea]);